spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
      server-addr: 192.168.100.8:8848
      username: nacos
      password: nacos
  datasource:
    druid:
      db-type: postgres
      initial-size: 4
      max-active: 8
      min-idle: 4
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://127.0.0.1:5432/test?currentSchema=seata
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.tiger.seata.stock.model
  mapper-locations: classpath:mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enabled: true
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  tx-service-group: test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      username: ${spring.cloud.nacos.username}
      password: ${spring.cloud.nacos.password}
      group: SEATA_GROUP
      application: seata-server
      namespace: public
#  config:
#    type: nacos
#    nacos:
#      server-addr: ${spring.cloud.nacos.server-addr}
#      username: ${spring.cloud.nacos.username}
#      password: ${spring.cloud.nacos.password}
#      group: SEATA_GROUP
  service:
    vgroup-mapping:
      test_tx_group: default
  client:
    rm:
      report-retry-count: 3
      report-success-enable: true
server:
  port: 8085
