spring:
  application:
    name: business-service
  cloud:
    nacos:
      discovery:
        group: SEATA_GROUP
      server-addr: 192.168.100.8:8848
      username: nacos
      password: nacos
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  tx-service-group: test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      username: ${spring.cloud.nacos.username}
      password: ${spring.cloud.nacos.password}
      group: SEATA_GROUP
      application: seata-server
  service:
    vgroup-mapping:
      test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: true
      report-retry-count: 3
server:
  port: 8084

