spring:
  application:
    name: business-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: SEATA_GROUP
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

seata:
  application-id: ${spring.application.name}
  enable-auto-data-source-proxy: false
  tx-service-group: test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      application: seata-server
  service:
    vgroup-mapping:
      test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: true
      report-retry-count: 3
server:
  port: 8084

